ansible_become_pass: ENC[AES256_GCM,data:xNRbeVq5/rwWLAc=,iv:/zsX/gjffRcZXvcWkux2y/rFMMS98ffjygc/nLIJ3dw=,tag:Ok4DZ/02jlyn+4xdKNP+tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSkNjbkd0RkJvOWZtRlFN
            dXpSZ2VRNGV6MHNMZ2U0QU0yMmQrbUU5dW04ClRKSjhSSEdGOUFMUkpUelpVTldi
            d2N1dnJHUHZKcjhraUhuTkJlSzcvUGMKLS0tIEpmNWxZcm93V2RhajM5dXJHaXNw
            WGpoUDdoQ2gzSkYvSmlBbGx0emlhWFUKmOuHuYbLFXTqpkWE4DEoSEB17/nuqrHk
            NX7GtpkIhZBCGwa2ii4oCkx+n4e16ldMMn4jsabk8jsXb3xtcqxiVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T09:56:05Z"
    mac: ENC[AES256_GCM,data:fZpvUP/Z+yBC3Hdf6RATTRgvjGNjX99eZkJZEpGT3YK+D5U1sOv2gh79RLb/RsNleOawtnenArtiRtQklb9d0f4eSDTbKO76ZAN0oKxT5kxWH2rrFJr5RkUcz61+WnkR0/cnMuvzu4pZuIvBlsKEa/Su+7e+5Kxo8mxWDgnD4F0=,iv:oMHqWOQ6fKzZI9qgL7toSVt+cUYpPZKb3kKBDgissoE=,tag:GXT6TDTu4I7TUNuLMuYeUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
