apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4sJw8qTWZ+EZQUooXzwAzpJHUxRI5fi1,iv:QZJTfcctcBFTflPHwSreGJIOE6UadGeAM/JKjy7T6io=,tag:I6efwYJ/vLM0he7dLcwrbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1487nq733vup0hn7sj2whkjw8ecqpwefgzsnghhyazuz2cvxu9adsyuk4hv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbEpDUHBiREhaUldGL2xS
            Um1scmVtOFBHV0JSWEVDVXN5VmVBUVBCc1hRCkJ0aEFJYXIwQUx3R3hWUzRiSHcy
            Vi85cTRLNTJzZ1JLaUFDZHNsb3lwaEEKLS0tIFdXUEFpSDF1ZDRVUHVTbEpoRUlG
            S1J2WUtaK3J4UUZUWmNmSFdCdTROU0EKno5jOdLhNrB8ScxxxgsoFTcJ4lIaUw6C
            5FVJBHoiQ1k75Xf24dcTvSyI06ksB8GlKyEFOX8D7fMCQCqnnEjA6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T19:27:12Z"
    mac: ENC[AES256_GCM,data:5uS1RdbuZoxLWvieG/slFBlqqhMfkDs5h7nZy6ubIuGPjL1o9cLySxVLSeCiwSyTL6R0Ldh2wgyQ1zLbXkONRnBIjaRJhDCaKz6kEjVpKx9aOcS21A8ysA9pUKzrRNfregczbdk97FJp8tCybxZBZ2N4DpHV3P2Q6hv+tTdu/+o=,iv:PQhzyrF75uqc1NP7+Etdd9CLqMhULlhKfA7rhIKffpw=,tag:okHE+1d3kvAAJMqewDHpZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
