---
kubernetes:
  children:
    master:
      hosts:
        kube-master1:
          ansible_user: kube-deploy
          ansible_host: 10.82.151.214
    worker:
      hosts:
        kube-worker1:
          ansible_user: kube-deploy
          ansible_host: 10.82.151.146
        kube-worker2:
          ansible_user: kube-deploy
          ansible_host: 10.82.151.186
