apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:C6pvvu9+wrkRhQVam9NEmTVk0rWLt/qC7G8vXj9TMiC0jlNiQNULdg==,iv:QMt15bPg0P+9YsZQxm39hx+UGgOoODOkfWapo/5VmWs=,tag:arcHKljhvuHWSMaaaXMJ6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU0JvNGZBZFpwaTV0dnFJ
            S01NQkRXem1kSkwrK0NFUVdlNkd4OTE2YVJrCjJKQ3BUakpBZFhVVVhQbVQ1TlZ5
            c1dCMHhVMm9ZdW0zNGlsWnQvdmlMNmcKLS0tIHMwQ1JVV0FPWUdRSTVua2lKOXg5
            Ym8zSlFRYU5JSHBRNnEvOEJlQzE5SlkKLqe6urnkuyNOuZ/1va34Iy7MPHnwB9oQ
            SCStg8qndXUAHbvdPI1hcz/ZRqflUd44t0LyQ02FTes1D76WUDxPiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T10:05:57Z"
    mac: ENC[AES256_GCM,data:2fh+6+MDqaG6/9vquaVEexq8dURCPMkAfptzfXPNkd2oYVKaP8VVF3UDSW7O4ist7aDMpZa2gvOwasZlJAZ5DDzmBDwNd9JID7eC208AqErKRyINen7Dhf4es2VofNIFNCmthMioiyFOzSTbaritOU3VKQSfmVopX/PO696KcH0=,iv:VRmJMRm4DyhRwEmKuzPNZtwjNVkczDPGd/hLMbrEPrQ=,tag:EXsE6VKU+G0CXHsaccaaPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
