apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:zCghUzH7clf6zC/wwV3BneyLAa058AyKB1dRdrw7mb5LTKDCuWuBKw==,iv:ZSxgfO2Y6bimsfx+uIJqGRp43b6qPXIT/1TBpMbHDM4=,tag:BAFn608ujojDzHTbDOadqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1487nq733vup0hn7sj2whkjw8ecqpwefgzsnghhyazuz2cvxu9adsyuk4hv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZktEaHhqWkRzQklLa0or
            U09tWEpSNndIRGJzQWpuQkJKR0p3OFp3eVdRCldmbnRvQUl2U01sUDBMMG4ra0hD
            Q3lBUFZ0UWRWaDVtM2grM0E2aWJLbDgKLS0tIEZINGxTQkszbVdmeDlud0NXOHpN
            K1BhZ1R5RUx5SXltRUc3U2lZbkQ1dWcKwoOEb2slMyKn2/MuA+5E/Ma16qFSODRT
            oCXrx3Q5FeaHrIbSgpZuhvCh1LhCnePOfGpSJlszzb/LLpYh7zuClA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T19:27:13Z"
    mac: ENC[AES256_GCM,data:bUoxdgiJ8sqyZkQJmm2tjb+clf8W+b7rfiv52sZ2m8R2RSthTvymNDhEk54H+R7mpf1e991zHP4hp0Q7TR5gz2iEcN6Xfi5iv3W8ehKqTSEg2b4E57zzmMg2XZvl5zE4a3fBvSIkRpAGXea8sWmaBbw/Asnp2nQ9i/iFNShcTuQ=,iv:nUHfAT0u81Q200roRs1yxDkme6yq3gGpO70iP0hJ2EU=,tag:wBcBgJNiGnXSQP6VQSCNjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
