apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:/7CT+fIh5s8dTlHxIPZXb8PQ3ulB/rS6tywsGQvyKdTzy7bBcLXzcA==,iv:2m9t1c1uSXd7UGGf22WyniuBBRkU2FA9tPNYVpeGxcw=,tag:JPWRZUtnuWQnl0K4Ra8hiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU1NCelowd3d1NFJIYWVq
            dkNoaktROFJHbmphQnlrc2xwZnlSZldlSm5vCitkQkFRUWpjSy8rM3dwODB2Sksr
            SGhLQldUZWx2QktsVHVHZTdVa2xUTUEKLS0tIDd0bUFGVlFRcEZmQndkQUU1SlY3
            T3NLd1doNk5Tc2hSK0QyTGxXcTREYmMKyGAEUT+9N1fdXF1dIaLQh58wPyxc2RzZ
            G9bBO1SuBpP61cm7cyTmmH+u7UTcvcV4VkgZB0xc3BvPfa8GhfypHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T09:56:57Z"
    mac: ENC[AES256_GCM,data:vMtqqXMmaMPjnqPDEesAwKlB8GLFrAvq5MCxhMArc1BN1r9IafoSm6PXdmnabCREtBaxpzJ050LHjGFYipp8n0+KGSDb9B7yOILbr+F2hod3aytmoXej97M4PD0vUv/jJE6pLkua/O/nS0+uGm0dpV5/WeBlNFAgbjWxc6oFfXM=,iv:a1llYcOr3mm/PdwInrZMx+9R0OQznTDvO2e/x+IdYoA=,tag:my9Z98weX0zS2Di3J4XbOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
