apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JsKHTb7GcVSWHh244nMaO12uRHeQsYGG,iv:jc61AnzeTCD73c2NQGsYV6xXVgN96IA/l6rFxeYidDQ=,tag:1Z186iJ5+vRKrLEF9Q009A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:o72CX5iMVkotA+b+mTxQbTHhXgKeL4yL3SpNGqPxMIfjt9Wa,iv:nk90R5l8gnTVySjYNwOqx06Qd/4Yq3r4MzIs/Fjt47M=,tag:3P4McDJPvN9byBiyGvVrzw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:db6DScA3ftFQkSz92MM=,iv:8mr5aoFX+inp5CN8UbZt6lPWdUMlThAtDofE9N8ocwk=,tag:RN1AcG9usKK4xKhOGinI6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1487nq733vup0hn7sj2whkjw8ecqpwefgzsnghhyazuz2cvxu9adsyuk4hv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMnR3UWVhYjhncG1IUzNz
            Uno2Y1dXT250U3BHalFWRm0zNmI4a1BvL3drCjVwY3JpVDkvWUlSbkwyM014UWsr
            cDFhWjlLMFJzWGlCUmQyUlVSNVlHMU0KLS0tIEZ0NHY5R0hjQW9DMiswNkxCSnNx
            czZLNThERk45NWY3NXphS3BmYkppZEkKWDd4cC7PjImF+x+H8YwMtYKV7kercR5b
            cbAKsSyDqjqgelcghMWgLQ4U0lX+X4BArGmymhj8I/q3LQEKFgoyjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T19:27:12Z"
    mac: ENC[AES256_GCM,data:00zV+VXearPr6LX/je/uJLlOHDPWrFGpgZIZAquMyFBXr8S1vHExJPQeGK3fdua92wLiFCzw7IAdbuKTmnk7qUdJ6uLuWWgBgLZpoJvhvWJKOIItJX4tSP2rBYfZ3A/WRZQKO1mGoDcbKiV6ZTqX5/GI1c9rljP3tYIGN0t2cv4=,iv:CtqKd/jHDgWvyogJozqBD2qiDXeed/zD3wguXDxQV58=,tag:DpUY5ns0Lc0peG1DecRCgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
