---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "10.82.151.30"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.82.151.0/24"
  CLUSTER_CIDR_V6: "fd78:c889:49fb:e0::/60"
  SERVICE_CIDR_V6: "fd78:c889:47fb:e0::/112"
