apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Ht7epx8Z6xX+6lfM,iv:5ojNWzHyCnVYgrMLmnm52Z+VHYkNpWjYQY4xTLFr42Q=,tag:kh3mKOzY7O5SC3aejzF33g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkVqdVBjVWVUaXQrSk9z
            NHFPWXoxOXVTZlp6VXduTGQ4TlJyTmpTMkJ3CjlXM0FNQmNIeFAxdkpZZGJCR1Ev
            ckVFaUx3L1BpcE53bVFVdmJoVVFycm8KLS0tIEdvekRMRFZUK1RDTTNRQ0xYckNJ
            TWx5RmxqT1JyL3Q0WmZIZWNRdG93RUkKdzRNpD+2pDcpFBSCTfNdWTeeebjxEc6Z
            uWgC5Uwk6aWuBxlD5KZrWISTLvTFoqyMC3yB/FwUQV0SyV9I06w+nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T09:56:56Z"
    mac: ENC[AES256_GCM,data:Q2UX3awyvFbRoiaEQuB0vGZDyQuyi31L/rAaNvfO+mB3TNmJTvJDiboZ/6mciZy3+n9K2npm8chzd/DFvZeejI3HZsJhAShO5KH1Uh5gvPbImvl4EQWdR0YJH+Swue+jAklvMEAeESvyMs3xZ2g0EE3TxCcPtuLwb8TRNESWu2Y=,iv:2sxao7JsXwGoeJc7S1gEEecnVMHtT0k0vjJhiATiyuA=,tag:iMWH0mGMEA9G6K53Jg713A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
