apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qAxgGvJSgyV3HPwmMDq6tv0DJYQEPbx1,iv:rC6pgPXhR6OI1T1/WjcA3b6SPcfTW7g8Din/DjOD4Ko=,tag:ktFL3He5eiX3Fj/3JW/m4A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OtkUpA925TERWWSA5cFnaO9vDEBomN9fTnEYzdLaINNHQla8,iv:Y2TLGo88ImYoXzI5JXv76vfqlPNp9Upb0v8wsGN9/Zg=,tag:j2X+q4zuQEAxiqZ3RRWdHg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Aso0eDJcoAaYFCCK/gs=,iv:bSamgjI6FRR9m5MYN4/jclQSxzPiMioBXKPpU07CO/w=,tag:mYpZ/K4zPCHzmaGyhyRyIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzhUYTl1ZUxreTZuN3Bm
            L0MwUXhJQ0tvd0k2ZGRFdlZ1MkhLTUEzNGt3CmwrdEZ1ZUwyMk1PczVyaTN3dmV5
            S3FxKzljMTZZcjhsTUpYemtBS0pwRzgKLS0tIFYxRjdlejJzRFp0QmlhSU1Gb05L
            b2NQbTlhVXhyNW8zQmJBYlhtTzNPTjQKw07M1En+016zYr4bvMsOIC4i4foC9ScV
            U6UFYIxPju8y3gKFXo5lzxcUr7XE9CdOkOG+juX4pxSqqa1Tfpn/Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T10:05:56Z"
    mac: ENC[AES256_GCM,data:XfvbZa+J1kZvPJM1ue2yWdpQ6ztVRjW2RXHWz585sZ1ZPRnIP7BrLCXTs6Wp0CNGCBZlvy/rEfyoTCypWwcmaWWOpEYVpScXzxXOZc3A/pAei5yLrj8P0AXQhb8HQQxRmujMlKIfgT+e5IkKLDqv4NVqKc/hKFtmFrhOM+0YadM=,iv:SLArgyj3NGY3d1GdPzkUiT2X9hysrGUvBTX6kjQqsF8=,tag:RMyrtaAhGbc1xBN+mrcGiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
