apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:dLbjkAHge4lAarN/3FMvwmx6vA8HjpP8ygKx+CmNIE+vvI3+,iv:mvkJkw+3+WFAmtjwJIfBzJuH0fixmzAFIFozPtFnjzE=,tag:Ha89OXirF/CsA3KauNfOHg==,type:str]
    credentials.json: ENC[AES256_GCM,data:jACmnc7/pTLAoTx0lieZO1HRzE9rWzhEhH3e7saA05p3LRA8ko1rudGEXZBGzD+SwG6Llff2HzOZIfGIHcD24iXVmSYDy15tjtbxdpngvtLYXUTyn9rOEOE6YmjeS2ljCA7aYuDTKluNvv58JAWsHCUJMvele5hk5tGEN2XvRLKw/R8XfJQlr7o7IYdyXS1YKuv4LGYe4p26+2zranXjHAXBuQG7nbAqZSLRqhtlkQ==,iv:hVeCsC+evwJlz1W4R+KGkSUTEOsmYo1N4v68QKpYp2Y=,tag:pxrbrDd8nn5021QWZRRV9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gttzrxzmpkqd233zzxf0x9h5hfwxnmsna5y7f6jr48s7rcfy5eus326a8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RERST0Z0UFBwRGhBOGxL
            S0pDOWdpZTlCVy9ISDltY2Vab1hKc3lHNGxrClJOTk9OcXcwQk1LZXRnZ1dGclZv
            aklSb09HSnkvYWQzV3MwSVVFUDM4T2sKLS0tIG9GZ3REMUxSMnJsYUcxWm5MRHE4
            YzZHZStrd3JNWXpaRE0vSU9EdXVxeTAKze63gNFxFQFAjd0s8JFG4NiYLEqPhjYJ
            4mh7OcxMgavoCy20pHuSQeb3DWixY5Sq5qvvppfqInTXibYtAFHeKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T10:05:57Z"
    mac: ENC[AES256_GCM,data:qh7/Q5E3+oZn1ffvygLqXYwge5YqaYbR6ScYGjdMXq5toMTDLOyyorAcL8ZhtTcp/lIZrlepSNJiWCwoWDcXnXehMWUiG+/TlM/pBdhupUS1Fm+wD9rDhpAFE5f8LEJPcnnavgaJYZSlcG0PphZRu/1Nc+OVwrogqshfNekckLI=,iv:GMo36187aQGepBSwhr5ZUt2C9+FvnyAdymqxhj9tP0k=,tag:1Os2NdCr0PJfkrcoFynccw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
